



local Heat = {}




--[[

Each chunk will have a heatmap array. This heatmap will be generated by taking the heat of each block in the chunk, and adding its 
heat value * insulation to neighboring blocks in the heatmap array. 


]]--
























































return
Heat